Begin decompiling nusys
ethteck/papermario pull request #54
Opened 2020-09-18 20:51 UTC by JoshDuMan

2020-09-18 20:53 UTC, ethteck commented
🐱

2020-09-18 20:55 UTC, deopdeop commented
hi - LinuxTerm#0001

2020-09-22 16:20 UTC, ethteck requested changes

2020-09-22 16:20 UTC, ethteck commented on src/os/nusys/nuContInit.c
> +    u8 contBits;
small thing but I prefer the initialization to happen on the same line it's declared if possible (as is in this case)

2020-09-22 16:20 UTC, ethteck commented on src/os/nusys/nuContRmbMgr.c
> +    u32 i;
Other small thing, but I think we should use consistent types for loop itreators (assuming both u32 and s32 work) and we've been using s32 so far

2020-09-22 16:20 UTC, ethteck commented on src/os/nusys/nuGfxPreNMIFuncSet.c
> +    OSIntMask intMask;
Same line declaration thing here too

2020-10-13 18:55 UTC, nanaian commented
Can probably fix those nits during merge / post-merge / without @JoshDuMan given its been ~20 days since review. @ethteck?

2020-10-14 17:44 UTC, ethteck approved these changes

2020-10-14 19:09 UTC, pixel-stuck approved these changes

2020-10-14 19:59 UTC, merged